### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Apaczer**
- add nfriedly static page
- fetch all external zips, videos (reencode and downsize) and move to `assets/`
- remove any MiyooCFW.wiki redirections
- rm any google.drive & other ex. download redirections (use internal from assets)
- rm unused markdown docs
- add Footer and Social links (discord, matrix)

This should make docs fully standalone so we can ditch wiki at last and don't rely on external sources (e.g. some youtube links are already dead).

### CODE REVIEW

**Comment by Apaczer** [comment]
@nfriedly is it ok we use screenshots and content from your [blog post](https://www.nfriedly.com/techblog/2021-10-10-v90-usb-c/) on our docs' pages? See [preview](https://miyoocfw--4.org.readthedocs.build/en/4/Fixing-USB-C-charging-on-the-PowKiddy-V90.htm), just putting all info in one domain

**Comment by Apaczer** [comment]
changed page to markdown so make it inline with rest "Modding" guides look: https://miyoocfw--4.org.readthedocs.build/en/4/Fixing-USB-C-charging-on-the-PowKiddy-V90/

**Review by nfriedly — APPROVED** [review]
Yeah, this is fine as long as it keeps the link back to the original there. You might want to omit the "P.S." bit after the conclusion.

BTW, here is the original markdown source: https://github.com/nfriedly/nfriedly.com/blob/c5e713d0c9bab593360dc9e40700e0f8d29ba23c/src/documents/techblog/2021-10-10-v90-usb-c.html.md - there's also higher resolution images at https://github.com/nfriedly/nfriedly.com/tree/master/src/files/img/blog/v90

**Comment by Apaczer** [comment]
> BTW, here is the original markdown source: https://github.com/nfriedly/nfriedly.com/blob/c5e713d0c9bab593360dc9e40700e0f8d29ba23c/src/documents/techblog/2021-10-10-v90-usb-c.html.md

Thanks and for the mod itself (seen people already doing it). Removed "P.S." 👍

**Pull request merged**
